---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-chaos-monkey
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          serviceAccountName: pod-chaos-monkey
          containers:
          - name: pod-chaos-monkey
            image: pod-chaos-monkey
            args:
            - -n
            - workloads
          restartPolicy: OnFailure
