---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-chaos-monkey
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-chaos-monkey
          containers:
          - name: pod-chaos-monkey
            image: pod-chaos-monkey
            args:
            - -n
            - workloads
            - --dry-run
          restartPolicy: OnFailure