---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-chaos-monkey

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-chaos-monkey-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-chaos-monkey-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: pod-chaos-monkey
roleRef:
  kind: ClusterRole
  name: pod-chaos-monkey-cluster-role
  apiGroup: rbac.authorization.k8s.io
